import Image1 from "../Images/placeholder-image-1.jpg";
import Image2 from "../Images/placeholder-image-2.jpg";
import Image3 from "../Images/placeholder-image-3.jpg";
import Image4 from "../Images/placeholder-image-4.jpg";

const FakeVideos = [
  {
    key: 1,
    image: Image1,
    title: "Hello world? Who is the Inventor of Hello world",
    channelName: "Truth Among us",
    time: "1 year ago",
    views: "1B views",
  },
  {
    key: 2,
    image: Image2,
    title: "Who made this website? This.com | WebsitePedia.com",
    channelName: "WebsitePedia.com",
    time: "3 months ago",
    views: "12M views",
  },
  {
    key: 3,
    image: Image3,
    title: "WTF is life? How to be lively?",
    channelName: "Filthyerr",
    time: "4 year ago",
    views: "29K views",
  },
  {
    key: 4,
    image: Image4,
    title: "My last message to all...",
    channelName: "R-Sauce",
    time: "10 year ago",
    views: "2K views",
  },
  {
    key: 5,
    image: Image1,
    title: "Hello world? Who is the Inventor of Hello world",
    channelName: "Truth Among us",
    time: "1 year ago",
    views: "4K views",
  },
  {
    key: 6,
    image: Image2,
    title: "Who made this website? This.com | WebsitePedia.com",
    channelName: "WebsitePedia.com",
    time: "3 months ago",
    views: "23K views",
  },
  {
    key: 7,
    image: Image3,
    title: "WTF is life? How to be lively?",
    channelName: "Filthyerr",
    time: "4 year ago",
    views: "1K views",
  },
  {
    key: 8,
    image: Image4,
    title: "My last message to all...",
    channelName: "R-Sauce",
    time: "10 year ago",
    views: "2K views",
  },
  {
    key: 9,
    image: Image1,
    title: "Hello world? Who is the Inventor of Hello world",
    channelName: "Truth Among us",
    time: "1 year ago",
    views: "20K views",
  },
  {
    key: 10,
    image: Image2,
    title: "Who made this website? This.com | WebsitePedia.com",
    channelName: "WebsitePedia.com",
    time: "3 months ago",
    views: "122K views",
  },
  {
    key: 11,
    image: Image3,
    title: "WTF is life? How to be lively?",
    channelName: "Filthyerr",
    time: "4 year ago",
    views: "12K views",
  },
  {
    key: 12,
    image: Image4,
    title: "My last message to all...",
    channelName: "R-Sauce",
    time: "10 year ago",
    views: "12K views",
  },
  {
    key: 13,
    image: Image4,
    title: "My last message to all...",
    channelName: "R-Sauce",
    time: "10 year ago",
    views: "2K views",
  },
  {
    key: 14,
    image: Image1,
    title: "Hello world? Who is the Inventor of Hello world",
    channelName: "Truth Among us",
    time: "1 year ago",
    views: "4K views",
  },
  {
    key: 15,
    image: Image2,
    title: "Who made this website? This.com | WebsitePedia.com",
    channelName: "WebsitePedia.com",
    time: "3 months ago",
    views: "23K views",
  },
  {
    key: 16,
    image: Image3,
    title: "WTF is life? How to be lively?",
    channelName: "Filthyerr",
    time: "4 year ago",
    views: "1K views",
  },
  {
    key: 17,
    image: Image4,
    title: "My last message to all...",
    channelName: "R-Sauce",
    time: "10 year ago",
    views: "2K views",
  },
  {
    key: 18,
    image: Image1,
    title: "Hello world? Who is the Inventor of Hello world",
    channelName: "Truth Among us",
    time: "1 year ago",
    views: "20K views",
  },
  {
    key: 19,
    image: Image2,
    title: "Who made this website? This.com | WebsitePedia.com",
    channelName: "WebsitePedia.com",
    time: "3 months ago",
    views: "122K views",
  },
  {
    key: 20,
    image: Image3,
    title: "WTF is life? How to be lively?",
    channelName: "Filthyerr",
    time: "4 year ago",
    views: "12K views",
  },
  {
    key: 21,
    image: Image4,
    title: "My last message to all...",
    channelName: "R-Sauce",
    time: "10 year ago",
    views: "12K views",
  },
  {
    key: 22,
    image: Image1,
    title: "Who made this website? This.com | WebsitePedia.com",
    channelName: "WebsitePedia.com",
    time: "3 months ago",
    views: "122K views",
  },
  {
    key: 23,
    image: Image2,
    title: "WTF is life? How to be lively?",
    channelName: "Filthyerr",
    time: "4 year ago",
    views: "12K views",
  },
  {
    key: 24,
    image: Image3,
    title: "My last message to all...",
    channelName: "R-Sauce",
    time: "10 year ago",
    views: "12K views",
  },
];

export default FakeVideos